export const CONSTANTS = {
    BASE_LEAD_VALUE_USD: 1200,
    REP_HOURLY_COST_USD: 70,
    SLA_MINUTES: 30,
    STALE_DAYS: 7,
    AVG_DUPLICATE_WASTED_HOURS: 2,
    UNASSIGNED_PENALTY_FACTOR: 0.5, // 50% risk
    NO_NEXT_STEP_PENALTY_FACTOR: 0.3 // 30% risk
};
